package ${basePackage}.entity;

${imports}
/**
 * ${entityName} entity.
 * Generated by REST API Generator.
 */
@Entity
@Table(name = "${tableName}")
public class ${className} {

${fieldsBlock}${relationshipBlock}${constructorBlock}${gettersBlock}}
